CREATE TABLE health_access_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region VARCHAR(40) NOT NULL UNIQUE,
    population BIGINT NOT NULL,
    elderly_population BIGINT NOT NULL,
    active_clinics BIGINT NOT NULL,
    elderly_share_pct NUMERIC(6, 2) NOT NULL,
    clinics_per_10k_elderly NUMERIC(8, 2) NOT NULL,
    priority_score NUMERIC(6, 2) NOT NULL,
    priority_band VARCHAR(16) NOT NULL,
    period VARCHAR(16) NOT NULL
);

CREATE INDEX idx_health_priority ON health_access_metric (priority_score DESC);

CREATE TABLE housing_market_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region VARCHAR(40) NOT NULL UNIQUE,
    transaction_count BIGINT NOT NULL,
    median_trade_price_krw BIGINT NOT NULL,
    median_price_per_sqm_krw BIGINT NOT NULL,
    median_area_sqm NUMERIC(8, 2) NOT NULL,
    price_cagr_pct NUMERIC(8, 2) NOT NULL,
    market_heat_score NUMERIC(6, 2) NOT NULL,
    market_band VARCHAR(16) NOT NULL,
    period VARCHAR(16) NOT NULL
);

CREATE INDEX idx_housing_heat ON housing_market_metric (market_heat_score DESC);

