"""Export processed marts and database seed SQL consumed by the Spring API."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def _sql_text(value: object) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def export_outputs(
    health: pd.DataFrame, housing: pd.DataFrame, processed_dir: Path, migration_path: Path
) -> None:
    processed_dir.mkdir(parents=True, exist_ok=True)
    migration_path.parent.mkdir(parents=True, exist_ok=True)
    health.to_csv(processed_dir / "health_access.csv", index=False, encoding="utf-8")
    housing.to_csv(processed_dir / "housing_market.csv", index=False, encoding="utf-8")

    lines = ["-- Generated by: python -m regional_insight.cli build", ""]
    for row in health.itertuples(index=False):
        lines.append(
            "INSERT INTO health_access_metric "
            "(region, population, elderly_population, active_clinics, elderly_share_pct, "
            "clinics_per_10k_elderly, priority_score, priority_band, period) VALUES "
            f"({_sql_text(row.region)}, {row.population}, {row.elderly_population}, "
            f"{row.active_clinics}, {row.elderly_share_pct}, {row.clinics_per_10k_elderly}, "
            f"{row.priority_score}, {_sql_text(row.priority_band)}, {_sql_text(row.period)});"
        )
    lines.append("")
    for row in housing.itertuples(index=False):
        lines.append(
            "INSERT INTO housing_market_metric "
            "(region, transaction_count, median_trade_price_krw, median_price_per_sqm_krw, "
            "median_area_sqm, price_cagr_pct, market_heat_score, market_band, period) VALUES "
            f"({_sql_text(row.region)}, {row.transaction_count}, {row.median_trade_price_krw}, "
            f"{row.median_price_per_sqm_krw}, {row.median_area_sqm}, {row.price_cagr_pct}, "
            f"{row.market_heat_score}, {_sql_text(row.market_band)}, {_sql_text(row.period)});"
        )
    migration_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

